# https://www.youtube.com/watch?v=e2tsBx6Q9zM&themeRefresh=1
# 
# 
# 
# memincr <- memory.limit()*100
# memory.limit(memincr)
# # up the limit to 1GB, this in bytes is 1014*1024^2 
# # options('future.globals.maxSize' = memory.limit(x))
# 
# # create clusters; dedicating 50 workers; for 72 cores
# require(furrr) %>% suppressMessages() %>% suppressWarnings()
# options('future.globals.maxSize' = (1014*1024^2)*7)
# 
# future::plan(list(future::tweak(future::multisession, workers = 5)))


source("getacleddata.R")
# Prepare ACLED data


# data by admin region ----------------------------------------------------

# library(cowplot)
library(ggtext)
library(tibbletime)
library(extrafont)
library(patchwork)

# Load fonts (assuming this function call is correct)
loadfonts(device = "pdf")

# Define the rolling sum function for a 7-day window
rolling_sum <- tibbletime::rollify(.f = sum, window = 7)

# Calculate the data for the heatmap
events %>% 
  st_drop_geometry() %>% 
  dplyr::select(event_date, fatalities, admin1Name, actor, notes)  %>% 
  filter(actor %in% c("Military Forces of Sudan (2019-)", "Rapid Support Forces")) %>% 
  filter(event_date > as.Date("2023-04-01")) %>% 
  sp::merge(
    x = sudan_boundaries %>% select(events %>% select_if(!names(.) %in% (names(events))) %>% names, "admin1Name"),
    y = .,
    by = "admin1Name", all.y = TRUE) %>% 
  group_by(event_date, admin1Name, actor) %>% 
  summarise(fatalities = sum(fatalities, na.rm = TRUE), .groups = 'drop') %>%
  # group_by(admin1Name, .drop=F) %>% 
  mutate(fatalitiestotal = sum(fatalities),
         eventstotal= sum(n()),
         namegroup = admin1Name) %>% 
  # arrange(event_date) %>% 
  ungroup %>% 
  # complete(event_date = seq(min(event_date), max(event_date), by = "day"), admin1Name, actor) %>% 
  mutate(
    month_year = format(event_date, "%b %Y"),  # New column for month and year
    month = month(event_date)) %>% 
  mutate(month_year = factor(month_year, levels = unique(month_year)))-> actor_fatalities  


# dates -------------------------------------------------------------------


# Define the time range for plotting
end.date <- max(actor_fatalities$event_date, na.rm = TRUE)
start.date <- as.Date("2023-04-01")
recentrange <- c(start.date , end.date + days(1))



# times series plots ------------------------------------------------------


plottimeseries <- function(x) {
  
  ggplot(data =x, aes(x = event_date, y = admin1Name, color = actor, size = fatalities)) +
    geom_point(data = x, alpha = 0.8) +
    scale_size_continuous(range = c(1, 10), name = "Number of Fatalities") +
    # scale_color_manual(values = c("#a6611a", "#dfc27d", "#80cdc1", "#018571", "#5e3c99"), 
                       # name = "Fatalities Enacted by") +  # Change legend title
    theme_minimal() +
    geom_vline(xintercept = end.date, show.legend = FALSE, lty = 2, lwd = 0.5, alpha = 0.8, color = "darkgrey") +
    labs(
      # title = NULL,
      # subtitle = glue::glue("{x %>% select(admin1Name) %>% unique}: Number of Fatalities by Actor and State over Time"),
      subtitle =  glue::glue("{x[['admin1Name']]}: Number of Fatalities by Actor and State over Time"),
      x = "Date",
      y = "Location",
      caption = glue::glue("Generated by geo:truth team at {Sys.time()} \n Data source: ACLED")) +
    scale_x_date(date_breaks = "weeks", date_labels = "%d", expand = c(0.01, 0.01)) +
    scale_y_discrete(position = "right") +
    guides(color = guide_legend(title.position = "top", title.hjust = 0.5)) +
    facet_wrap(~month_year, scales = "free_x", nrow = 1, ncol = 20, strip.position = "top") +
    theme(
      plot.title = element_text(color = "#d73027", size = 80, family = "Roboto Condensed", face = "bold.italic"),
      plot.subtitle = element_text(color = "darkgrey", size = 30),
      text = element_text(size = 12, family = "Roboto Condensed"),
      axis.title.y = element_blank(),
      axis.title.x.bottom = element_blank(),
      plot.caption = element_text(size = 10, color = "darkgrey", hjust = 1),
      legend.text = element_text(size = 15),  # Increase legend text size
      axis.text.x = element_text(angle = 0, size = 10, vjust = 0.5, hjust = 1),
      axis.ticks.x = element_line(color = "black", size = 0.5),  # Darker ticks on x-axis
      legend.position = "bottom",
      legend.key.height = unit(2, "lines"),  # Adjust legend key height
      # strip.text.x = element_text(size = 12, color = "black")
    )#->plot_fatalities_over_time 
}
 

# Plotting
actor_fatalities %>% ungroup %>% 
  filter(!is.na(admin1Name)) %>% 
  mutate(namegroup = admin1Name ) %>% 
  group_by(namegroup, .drop=F) %>%
  arrange(namegroup,.by_group = T) %>% 
  named_group_split(namegroup) %>% 
  # head (2)  %>%
  purrr::map(.x= .,
             .f= safely(plottimeseries))->timeseriesplots





















# Calculate total fatalities by actor
events %>% 
  filter( event_date >= as.Date("2023-04-01")) %>% 
  group_by(actor) %>%
  summarise(total_fatalities = sum(fatalities, na.rm = TRUE)) %>%
  mutate(percent_fatalities = (total_fatalities  * 100/ sum(total_fatalities)))-> actor_fatalities_summary 

# Plotting the lollipop chart
ggplot(actor_fatalities_summary, aes(x = percent_fatalities, y = reorder(actor, percent_fatalities), color = actor)) +
  geom_segment(aes(x = 0, xend = percent_fatalities, y = actor, yend = actor), size = 4.3, alpha = 0.65, linewidth = 1.7) +  # Adjust height parameter
  geom_point(size = 20,alpha = .65) +
  geom_text(aes(label = actor, color= actor), nudge_x = -4, nudge_y = 0.5, family = "Roboto Condensed", size = 8) +
  geom_text(aes(label = paste0(round(percent_fatalities), "%")), nudge_x = -1.8, hjust = 0, color = "black", fontface="bold", family = "Roboto Condensed", size = 8) +
  scale_color_manual(values = c("#a6611a", "#dfc27d", "#80cdc1", "#018571", "#5e3c99")) +
  scale_y_discrete(position = "right",expand = expansion(mult = 1)) + #space between line segments
  scale_x_continuous( limits = c(0, 100)) +
  # scale_y_discrete(position = "right") +
  labs(title = NULL,
       subtitle = "Percentage of Total Fatalities by Actor in Sudan Conflict Since April 2023") +
  theme_minimal() +
  
  theme(
    plot.title = element_text(color = "#d73027", size = 80, family = "Roboto Condensed", face = "bold.italic"),
    plot.subtitle = element_text(color = "darkgrey", size = 30),
    text = element_text(size = 12, family = "Roboto Condensed"),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x  = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.x = element_blank(),
    panel.grid   = element_blank(),
    panel.spacing.y = unit(1, units = "in"), 
    plot.margin = unit(c(t=0, r=0, b=0, l=-.5), "in"),  # Add left margin to shift the plot content to the left
  ) +ggtitle("Telling a War Story | Sudan.")-> plot_percent_fatalities


# Combine plots
plot_percent_fatalities + plot_fatalities_over_time+
  plot_layout(widths = c(5,10),
              ncol = 1, 
              heights = c(4, 25)# Adjust heights to make the lollipop chart bigger
  )  ->combined_plot 

# Save the combined plot
ggsave("plots/combined_plot.png", combined_plot, width = 21, height = 27, units = "in", limitsize = FALSE)

