# plottimeseries <- function(x) {
#   enddate <- ceiling_date(today(), "month")
#   actor_order <- c("MSF", "RSF", "Another Group")
#   
#   ggplot(data = x, aes(x = month_year, y = percent, color = actor, size = fatalities)) +
#     geom_point(alpha = 0.8) +
#     
#     # Standardize size scale for fatalities
#     scale_size_continuous(
#       range = c(5, 15),
#       name = "Fatalities",
#       breaks = c(0,  10,  50, 100),
#       labels = c("0",  "10",  "50", "100+")
#     ) +
#     
#     # Ensure the x-axis starts from April 1, 2023 with weekly breaks
#     # scale_x_date(
#     #   limits = c(as.Date("2023-04-01"), enddate),
#     #   date_breaks = "1 day",
#     #   date_labels = "%d",
#     #   expand = c(0.01, 0.01)
#     # ) +
#     
#     # Fix other aesthetics
#     # scale_y_discrete(position = "right") +
#     # scale_color_manual(name ="Actors", 
#     #                    values = c("MSF" = "red", "RSF" = "green", "Another Group" = "#0000FF"), 
#     #                    breaks = actor_order, 
#     #                    labels = actor_order) +
#     
#     # Add vertical line for the end date
#     # geom_vline(xintercept = enddate, show.legend = FALSE, lty = 2, lwd = 0.5, alpha = 0.8, color = "darkgrey") +
#     
#     # Labels and captions
#     labs(
#       subtitle = glue::glue("{x[['admin1Name']]}: Fatalities by Actor and State over Time"),
#       x = "Date",
#       y = "Location",
#       caption = glue::glue("Generated by geo:truth team at {Sys.time()} \n Data source: ACLED")
#     ) +
#     
#     # Standardize legend and appearance
#     guides(color = guide_legend(title.position = "top", title.hjust = 0.5)) +
#     theme_minimal() +
#     theme(
#       plot.subtitle = element_text(color = "darkgrey", size = 40),
#       text = element_text(size = 35, family = "Roboto Condensed"),
#       axis.title.y = element_blank(),
#       axis.title.x.bottom = element_blank(),
#       plot.caption = element_text(size = 10, color = "darkgrey", hjust = 1),
#       legend.text = element_text(size = 35),
#       axis.text.x = element_blank(),
#       axis.text.y = element_blank(),
#       axis.ticks.x = element_line(color = "black", size = 0.5),
#       legend.position = "bottom",
#       legend.key.height = unit(2, "lines")
#     ) +
#     
#     # Facet wrapping by month and year
#     facet_wrap(~month_year, scales = "free_x", nrow = 1, ncol = 20, strip.position = "top")
# } #works
# recentrange <- c(start.date , enddate + days(1))
# 
# events %>%
#   # filter(disorder_type %in% "Political violence") %>%
#   select(event_date, fatalities, admin1Name, actor, latitude, longitude) %>%
#   arrange(event_date) %>%
#   filter(event_date >= as.Date("2023-04-01")) %>%
#   group_by(event_date, admin1Name, actor) %>%
#   summarise(fatalities = sum(fatalities, na.rm = TRUE), .groups = 'keep') %>% 
#   mutate(
#     month_year = format(event_date, "%b %Y"),  # New column for month and year
#     month = month(event_date)) %>%
#   ungroup() %>% 
#   complete(admin1Name = unique(sudan_boundaries$admin1Name)
#            # event_date
#            , fill = list(fatalities = 0)
#   )->actor_fatalities
#   
#   
#   
# Ensure date continuity and fill in missing data for the time series
# events %>%
#   filter(event_date >= as.Date("2023-04-01")) %>%
#   group_by(event_date, admin1Name, actor) %>%
#   summarise(fatalities = sum(fatalities, na.rm = TRUE), .groups = 'keep') %>%
#   ungroup() %>%
#   complete(
#     event_date = seq.Date(from = min(event_date), to = max(event_date), by = "day"),
#     admin1Name = unique(events$admin1Name),
#     fill = list(fatalities = 0)
#   ) %>%
#   mutate(month_year = format(event_date, "%b %Y")) %>% 
#   mutate(  # New column for month and year
#     month = lubridate::month(event_date),
#     actor = case_when(
#       grepl(pattern = "Military Forces of Sudan|Government of Sudan", x = actor) ~ "MSF",
#       grepl(pattern = "Rapid Support Forces", x = actor) ~ "RSF",
#       grepl(pattern = "Militia|Group", x = actor) ~ "Another Group",
#       TRUE ~ "Another Group"
#     )
#   ) %>%
#   mutate(month_year = factor(month_year, levels = unique(month_year)))-> actor_fatalities














sudan_boundaries %>% 
  mutate(
    maxlat= max(st_coordinates(sudan_boundaries$geometry[,1])
      )) %>% view





custom_palette <- c("#FFE6E0", "#FCCAC0", "#F8A9A1", "#F78C81", "#F8766D")


eventsbytypeactorgeo %>%
  st_drop_geometry() %>%
  pivot_wider(names_from = actorshort, 
              values_from = c(counts, percent),
              names_sep = "") %>%
  ungroup() %>% 
  merge( 
    sudan_boundaries %>%  
      mutate(centroid = st_centroid(geometry),
             long = st_coordinates(centroid)[, 1],
             lat= max(st_coordinates(sudan_boundaries$geometry[,1])
                   # lat = st_coordinates(centroid)[, 2]
                   ) %>% 
            dplyr::select(long, lat, admin1Name) %>% distinct(admin1Name, .keep_all = T) %>% 
            st_drop_geometry(),
          all.y = T) %>%   view
  bind_rows(
    tibble(
      admin1Name = "RandomAdmin1")) %>% 
  
  
  mutate(across(where(is.numeric), ~ replace_na(., 0))) %>% 
  mutate(
    
    total_label = glue::glue("<b>{admin1Name}</b> <br> MSF: ({countsMSF}) {round(percentMSF, 0)}% | RSF: ({countsRSF}) {round(percentRSF, 0)}%"),         
    total_label = case_when(admin1Name == "RandomAdmin1" ~ glue::glue("<b>Admin Area Name</b><br>  Actor Name: (# of events per actor in area) % of events attributed to actor per region
                                                                      <br><br> -MSF: Military Forces of Sudan (2019-)
                                                                      <br> -RSF: Rapid Support Forces
                                                                      <br><br> Calculations include any type of armed conflict event that is within the adminstrative regions of Sudan.
                                                                      <br> Data Source: <b>ACLED</b>"), TRUE~ total_label),
    countsMSF   = case_when(admin1Name == "RandomAdmin1" ~ 0, TRUE ~ countsMSF),
    countsRSF   = case_when(admin1Name == "RandomAdmin1" ~ 0, TRUE ~ countsRSF),
    percentMSF  = case_when(admin1Name == "RandomAdmin1" ~ 0, TRUE ~ percentMSF),
    percentRSF  = case_when(admin1Name == "RandomAdmin1" ~ 0, TRUE ~ percentRSF),
    totalcounts = case_when(admin1Name == "RandomAdmin1" ~ 1, TRUE ~ totalcounts),
    long        = case_when(admin1Name == "RandomAdmin1" ~ 28.41388, TRUE ~ long),
    lat         = case_when(admin1Name == "RandomAdmin1" ~ 9.78632, TRUE ~ lat )) %>% 
  mutate(
    total_label = dplyr::case_when(totalcounts == 0 ~ paste(admin1Name), TRUE ~ (total_label)),
    nudge_x = case_when(
      admin1Name == "South Darfur" ~ 0,       
      admin1Name == "RandomAdmin1" ~ 7,      
      TRUE ~ 0),
    nudge_y = case_when(
      admin1Name == "South Darfur" ~ -1,
      admin1Name == "RandomAdmin1" ~ -3,
      TRUE ~ 0
    ),
    segment_x = long,  
    segment_y = lat,   
    end_x = long + nudge_x, 
    end_y = lat + nudge_y
  ) -> sudanregion_label
  
  
  
  
  
  
  
  
  plottimeseries <- function(x) {
    ggplot(data = x, aes(x = month_year, y = percent, fill = actor)) +
      
      # Use geom_col for clean, stacked bar visualization
      geom_col(position = "jitter", alpha = 0.9, width = 0.2) +
      
      # Standardize the y-axis to display percentages (0-100%)
      scale_y_continuous(position = "right",
                         limits = c(0, 100),
                         breaks = seq(0, 100, by = 25),
                         labels = function(x) paste0(x, "%"),
                         expand = c(0, 0)
      ) +
      
      # Customize colors in a sleek, minimal palette
      scale_fill_manual(
        name = NULL,  # Remove title for a cleaner look
        values = c("MSF" = "#FCCAC0", "RSF" = "#F8766D", "Another Group" = "darkgrey"),
        breaks = c("MSF", "RSF", "Another Group"),
        labels = c("MSF", "RSF", "Another Group")
      ) +
      
      # Add labels and captions
      labs(
        # title = "% of Fatalities by Actor per State | Sudan",
        x = NULL,  # Remove x-axis label for simplicity
        y = NULL,  # Remove y-axis label
        caption = glue::glue("Data source: ACLED | Generated by geo:truth team at {format(Sys.time(), '%Y-%m-%d')}")
      ) +
      
      # Minimalist theme inspired by World Economic Forum style
      guides(color = guide_legend(title.position = "top", title.hjust = 0.5)) +
      theme_minimal() +
      theme(
        plot.title = element_markdown(family = "Roboto Condensed", size = 40, face = "plain", hjust = 0.5, margin = margin(b = 15)),
        plot.subtitle = element_text(color = "darkgrey", size = 40),
        text = element_text(size = 35, family = "Roboto Condensed"),
        # axis.title.y = element_blank(),
        axis.title.x.bottom = element_blank(),
        plot.caption = element_text(family = "Roboto Condensed", size = 10, color = "darkgrey", hjust = 1),
        legend.text = element_text(family = "Roboto Condensed", size = 35),
        axis.text.x = element_blank(),
        axis.ticks.x = element_line(color = "black", size = 0.5),
        legend.position = "top",
        legend.key.height = unit(2.4, "lines"),
        strip.background.x = element_rect(fill = "grey90", color = "grey90"),  # Grey color for facet strips
        panel.spacing = unit(.1, "lines")  # Add space between facet panels
        
      ) +
      
      facet_wrap(~month_year,dir = 'h', scales = "free_x", nrow = 1, ncol = 20, strip.position = "top") +
      ggtitle(glue::glue("% of Fatalities by Actor per State | <span style='color:#F8766D;'>Sudan</span>."))
    
    # ggtitle = glue::glue("% of Fatalities by Actor per State <span style='color:#F8766D;'>Sudan</span>")
    
  }
  
  
  
  # ggplot() +
  #   geom_sf(data = sudan_boundaries, alpha = .15) +
  #   theme_bw() +
  #   theme(text = element_text(size = 13, family = "RobotoCondensed-Regular")) +
  #   geom_sf(data = sudan_boundaries %>% 
  #             base::merge(x=.,y=sudanregion_label %>% dplyr::select(admin1Name, ,
  #                                                                   contains(c("count", "percent"))), 
  #                         all.x=T) %>% filter(totalcounts > 0),
  #           mapping = aes(fill = "Regions with at least 1 armed conflict event within the date range."),
  #           linewidth = 0.1
  #   ) +
  #   geom_segment(
  #     data = sudanregion_label %>% filter(admin1Name %in% c("Bahrain", "United Arab Emirates", "Qatar")),
  #     aes(x = segment_x, y = segment_y, xend = end_x, yend = end_y),
  #     color = "#333333", # Color of the line segment
  #     size = 0.5
  #   ) +
  #   geom_richtext(
  #     data = sudanregion_label,
  #     aes(x = long + nudge_x, y = lat + nudge_y+ ., label = total_label),
  #     size = 9,
  #     family = "RobotoCondensed-Regular",
  #     fill = ifelse(sudanregion_label$totalcounts > 0, no = NA, yes = "#333333"),  # Conditional fill
  #     colour = ifelse(sudanregion_label$totalcounts == 0, no = "white", yes = "grey68"),  # Conditional fill
  #     label.color = NA, # Removes border around text
  #   ) +
  #   theme_bw() +
  #   labs(
  #     subtitle = glue::glue("{startdate %>% format('%A, %B %d, %Y')} to {enddate %>% format('%A, %B %d, %Y')} \n \n"),
  #     caption = glue::glue("\nGenerated by <span style='color:#00BFC4;'>geo:truth Team</span> at {Sys.time()}    _")
  #   ) +
  #   theme(
  #     strip.text.y.left = element_text(size = rel(1.5), color = "#333333", face = "bold", 
  #                                      family = "RobotoCondensed-Regular", margin = margin(r = 10),
  #                                      angle = 0),
  #     strip.background = element_blank(),
  #     strip.text = element_text(size = rel(1), color = "#333333", margin = margin(), family = "RobotoCondensed-Regular"),
  #     panel.spacing = unit(3, "pt"),
  #     plot.title = element_markdown(size = 95, lineheight = .9, face = "bold.italic", family = "RobotoCondensed-Regular"),
  #     plot.subtitle = element_text(size = 60, face = "plain", family = "RobotoCondensed-Regular"),
  #     plot.caption = element_markdown(size = 40, family = "RobotoCondensed-Regular"),
  #     legend.text = element_text(size = 40, family = "RobotoCondensed-Regular"),
  #     axis.line.x.top = element_line(),
  #     axis.line.x.bottom = element_line(),
  #     panel.grid.major = element_blank(),
  #     panel.grid.minor = element_blank(),
  #     panel.border = element_blank(),
  #     axis.text.x = element_blank(),
  #     axis.ticks.x = element_blank(),
  #     axis.text.y = element_blank(),
  #     axis.title = element_blank(),
  #     axis.ticks.y = element_blank(),
  #     axis.line.y = element_blank(),
  #     plot.background = element_rect(fill = NA, color = NA),
  #     panel.background = element_rect(fill = NA, color = NA),
  #     legend.title = element_blank(),
  #     legend.position = "top"
  #   ) +
  #   ggtitle(glue::glue("Armed Conflict Events | <span style='color:#F8766D;'>Sudan</span>."))
  # 
  # 
  # ggsave(here::here(getwd(), "plots", "actors.pdf"),
  #        width = 36,  # Increase width
  #        height = 46,  # Increase height
  #        device = cairo_pdf
  # )
  # 
  # 
  # 
  plottimeseries <- function(x) {
    enddate <- ceiling_date(today(), "month")
    actor_order <- c("MSF", "RSF", "Another Group")
    
    ggplot(data = x, aes(x = event_date, y = admin1Name, color = actor, size = fatalities)) +
      geom_point(alpha = 0.8) +
      
      # Standardize size scale for fatalities
      scale_size_continuous(
        range = c(5, 15),
        name = "Fatalities",
        breaks = c(0,  10,  50, 100),
        labels = c("0",  "10",  "50", "100+")
      ) +
      
      # Ensure the x-axis starts from April 1, 2023 with weekly breaks
      scale_x_date(
        limits = c(as.Date("2023-04-01"), enddate),
        date_breaks = "1 day",
        date_labels = "%d",
        expand = c(0.01, 0.01)
      ) +
      
      # Fix other aesthetics
      scale_y_discrete(position = "right") +
      scale_color_manual(name ="Actors", 
                         values = c("MSF" = "red", "RSF" = "green", "Another Group" = "#0000FF"), 
                         breaks = actor_order, 
                         labels = actor_order) +
      
      # Add vertical line for the end date
      # geom_vline(xintercept = enddate, show.legend = FALSE, lty = 2, lwd = 0.5, alpha = 0.8, color = "darkgrey") +
      
      # Labels and captions
      labs(
        subtitle = glue::glue("{x[['admin1Name']]}: Fatalities by Actor and State over Time"),
        x = "Date",
        y = "Location",
        caption = glue::glue("Generated by geo:truth team at {Sys.time()} \n Data source: ACLED")
      ) +
      
      # Standardize legend and appearance
      guides(color = guide_legend(title.position = "top", title.hjust = 0.5)) +
      theme_minimal() +
      theme(
        plot.subtitle = element_text(color = "darkgrey", size = 40),
        text = element_text(size = 35, family = "Roboto Condensed"),
        axis.title.y = element_blank(),
        axis.title.x.bottom = element_blank(),
        plot.caption = element_text(size = 10, color = "darkgrey", hjust = 1),
        legend.text = element_text(size = 35),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_line(color = "black", size = 0.5),
        legend.position = "bottom",
        legend.key.height = unit(2, "lines")
      ) +
      
      # Facet wrapping by month and year
      facet_wrap(~month_year, scales = "free_x", nrow = 1, ncol = 20, strip.position = "top")
  } #works
  
  
